### ISSUE TITLE
cannot connect as admin

### ISSUE THREAD

**Issue by jgranduel** [soyuka/explorer#19]
Hi, 

I cannot connect as admin:admin during first connection. No clue about what is wrong...
(testing with iojs-3.3.0)

Thanks for any help.
Best regards, 
jgr

**Comment by soyuka** [comment]
iojs-3+ is sadly not supported because bcrypt can't compile, at least from what I've tested so far...

https://github.com/soyuka/explorer/commit/e758c8d06f160aee13aa424af1387e178bb9d035

**Comment by soyuka** [comment]
https://travis-ci.org/soyuka/explorer/jobs/81913818

By installing g++-4.8 travis is good to go.
