### ISSUE TITLE
Can't run it !

### ISSUE THREAD

**Issue by BloodMan29** [soyuka/explorer#29]
Hi !

I follow the install guide but i'm having troubles btw look awsome :D
After installing nodejs 4.4.2 and pm2, I install explorer, after it's done it won't start and crashed immediately here's logs:

http://pastebin.com/mAm8WC5g // pm2/logs/xplorer-error-0.log

http://pastebin.com/scssejE1 // pm2/logs/xplorer-out-0.log 
btw i don't know why it's not creating conf file in the directory and even if i create one it'll crash..

http://pastebin.com/tXi0hcd6 // installation + "pm2 show" after explorer's installation

And also I'm new to nodejs and all that stuff don't be harsh with me :)

Best regards,

PS: Es-tu français, j'ai vu ton nom quelque part je crois ? Merci

**Comment by BloodMan29** [comment]
I've temporarily installed it via git and it work well ;)

**Comment by soyuka** [comment]
Configuration was missing, it's usually in `~/.config/explorer/config.yml`, a default one is available [there](https://github.com/soyuka/explorer/tree/master/doc/examples).

You can also copy the entire directory:

```
cp -r doc/examples ~/.config/explorer
```
