### ISSUE TITLE
Browsing is very slow

### ISSUE THREAD

**Issue by Bbertatum** [soyuka/explorer#39]
Hi I use your nice piece of software to expose backup directories made from ZFS snapshots.

This issue is like a config tips.

After hours of searching I finnaly found that the issue was the calculation of directory size which is false when there is more than 10 directory levels 

To get rid of the slow browsing just edit .config/explorer/config.yml with maxDeph:1 

```
tree:
  # When calculating directory size we stop at the max_depth
  maxDepth: 1 #Default 10

```
Maybe this setting could became default ? 

Thanks again for your work I love that explorer :)

**Comment by soyuka** [comment]
The setting is exactly designed for this issue. Sorry but in my case it's smooth with a depth of 10 :smile:.

Glad you enjoy this project! (note if you can try to use `master` branch it has some bug fixes).
