### ISSUE TITLE
Autologin or disable login

### ISSUE THREAD

**Issue by bkanuka** [soyuka/explorer#42]
Is it possible to set a user to auto login?

I'm going to proxy this behind another webserver that does the https and auth for me already. No need to ask the user to log in again (and maintain a separate auth system)

**Comment by soyuka** [comment]
In config:
```
auth: false
user: admin #you can edit his path in ~/.config/explorer/data/users
```

**Comment by bkanuka** [comment]
Thanks. Do you have this (and other config settings) documented anywhere?

**Comment by soyuka** [comment]
:D added it to the README I think

**Comment by bkanuka** [comment]
I believe the right config option is `username`.

**Comment by soyuka** [comment]
https://github.com/soyuka/explorer/commit/ff466b342674cf041cbeffbc9ba7d2fddd6a9e86#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R76 it's `user`
